apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "go-kube-downscaler.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "go-kube-downscaler.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "go-kube-downscaler.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "go-kube-downscaler.selectorLabels" . | nindent 8 }}
      {{- if or .Values.podAnnotations .Values.forceRestartOnConfigChange }}
      annotations:
        {{- if .Values.forceRestartOnConfigChange }}
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- end }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "go-kube-downscaler.serviceAccountName" . }}
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          args:
          - --include-resources={{ join "," .Values.includedResources }}
          {{- with .Values.extraArguments }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
          {{- with .Values.arguments }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
          {{- if eq (include "go-kube-downscaler.leaderElection" .) "true" }}
          - --leader-election
          {{- end }}
          {{- if .Values.metrics.enabled }}
          - --metrics
          {{- end }}
          {{- if .Values.constrainedNamespaces }}
          - --namespace={{ join "," .Values.constrainedNamespaces }}
          {{- end }}
          {{- if .Values.metrics.enabled }}
          ports:
            - containerPort: 8085
          {{- end }}
          envFrom:
          - configMapRef:
              name: {{ .Values.configMap.name }}
              optional: true
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.healthProbes.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            failureThreshold: {{ .Values.healthProbes.readinessProbe.failureThreshold }}
            initialDelaySeconds: {{ .Values.healthProbes.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.healthProbes.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.healthProbes.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.healthProbes.readinessProbe.successThreshold }}
          {{- end }}
          {{- if .Values.healthProbes.readinessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            failureThreshold: {{ .Values.healthProbes.livenessProbe.failureThreshold }}
            initialDelaySeconds: {{ .Values.healthProbes.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.healthProbes.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.healthProbes.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.healthProbes.livenessProbe.successThreshold }}
          {{- end }}
          {{- if .Values.healthProbes.startupProbe.enabled }}
          startupProbe:
            httpGet:
              path: /healthz
              port: 8081
            failureThreshold: {{ .Values.healthProbes.startupProbe.failureThreshold }}
            initialDelaySeconds: {{ .Values.healthProbes.startupProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.healthProbes.startupProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.healthProbes.startupProbe.timeoutSeconds }}
            successThreshold: {{ .Values.healthProbes.startupProbe.successThreshold }}
          {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
